### ISSUE TITLE
Erreur 36

### ISSUE THREAD

**Issue by Jclaude49** [KevinBonnoron/the_keys#31]
Bonjour Kevin,

Je suis tombé sur l'intégration TheKeys, elle est bien installé dans "/homeassistant/custom_components/the_keys/".
J'ai bien le partage dans "api.the-keys"

Quand je veux ouvrir dans home assistant je reçois l'erreur  "36" et dans the-keys "Code invalide".

Merci pour l'aide
![erreur_thekeys](https://github.com/user-attachments/assets/98ed7181-3766-48f5-a027-8844e53052b5)
![log_thekey](https://github.com/user-attachments/assets/e305429f-e1d0-4af9-9b4f-2ef81ef24eab)

**Comment by KevinBonnoron** [comment]
Bonjour Jclaude49,

Est-ce que par hasard vous auriez ajouter un code pour ouvrir la serrure ?

**Comment by Jclaude49** [comment]
Merci de m'avoir répondu, sur le partage thekeys,il y a un code mais je n'ai rien mis sur home assistant

![partage_thekeys](https://github.com/user-attachments/assets/7882f092-5f47-489b-9feb-4808eefeba95)

**Comment by KevinBonnoron** [comment]
Je viens de remarquer que le partage à été créé en date du 28 août mais que la log d'erreur date du 13 août. Est-ce que ce n'est pas un ancien log qui plantait ? C'est toujours le cas aujourd'hui ?

Sinon autre possibilité, la gateway n'est pas à jour. Il me semblait avoir vu dans les changelog de TheKeys qu'ils avaient corrigé un soucis de gestion de code à un moment. Ma Gateway est en version 65.

**Comment by Jclaude49** [comment]
Ma gateway semble à jour, pour le log, je n'avais pas pris le bon mais c'est le même message
![message_gateway](https://github.com/user-attachments/assets/35cb4ec8-97f0-4cfb-834a-0cc16bc1c96c)
![log_thekeys](https://github.com/user-attachments/assets/e830a47e-86ec-474b-ae96-45666969b4e7)
![gateway](https://github.com/user-attachments/assets/e03f5cbc-bac2-4415-94a4-14d8e7a254ab)

**Comment by Jclaude49** [comment]
Bonjour Kevin,
je le trouve ou ce code invalide.

Merci

**Comment by KevinBonnoron** [comment]
Bonjour Jclaude49,

Désolé pour ma réponse tardive. Je pensais à un code nécessaire pour ouvrir la serrure pour la sécurité mais en effet il n'y a pas moyen via l'application d'en ajouter.
J'ai comparé vos captures avec les miennes et je ne vois rien d'anormal.

Est-ce que vous avez quelque chose dans la partie "partage" ?

**Comment by Jclaude49** [comment]
Merci Kevin,

en partage, je n'ai que les partages users(voir copie écran) et en accessoires, une télécommande et la gateway (en copie plus haut).
J'avais viré du logiciel Jeedom, le plugins "the keys" avec lequel ça fonctionnait.
Quand je tape l'adresse IP de la gateway, j'ai cette réponse: {"version": "65", "current_status": "Scanning"}.
Je soupçonne un problème de la gateway mais la société "TheKeys" aurait semble t'il abandonné les serrures connectées et ne répond plus aux mails.

Bon WE
![Partages_accessoires](https://github.com/user-attachments/assets/7a90d735-4641-4560-9b0d-307bc938e2a8)
![Partages_Users](https://github.com/user-attachments/assets/02499fec-d35c-4cf0-9fb2-1839c8f455e2)

**Comment by KevinBonnoron** [comment]
Est-ce que dans les logs de HomeAssistant vous avez quelque chose ?

**Comment by Jclaude49** [comment]
[Log_thekeys.txt](https://github.com/user-attachments/files/16821581/Log_thekeys.txt)

**Comment by KevinBonnoron** [comment]
Bonjour Jclaude49,

En regardant la documentation officielle de TheKeys (https://help.the-keys.fr/knowledge-base/controler-la-serrure-avec-la-gateway/) il semblerait que soit le partage soit invalide (ça n'a pas l'air d'être le cas), soit la serrure n'est pas synchronisée ce qui peut être le cas.
Sur la première page ou il y a les informations de la serrure, est-ce que vous pouvez vérifier que vous avez ça sur la colonne de droite ?
![image](https://github.com/user-attachments/assets/d535c266-9b83-4d8f-9cf9-8392bf532eb1)

**Comment by Jclaude49** [comment]
Bonsoir Kevin,
ma serrure est bien connectée mais je n'ai pas la même version. peut-on la mettre à jour ?
Merci
![page_serrure](https://github.com/user-attachments/assets/562337d1-59ca-45c6-9fd3-7ffd572b26f2)

**Comment by KevinBonnoron** [comment]
Depuis l'application mobile en allant dans la configuration de la serrure, puis tout en bas "Installer la mise à jour".

**Comment by Jclaude49** [comment]
Bonjour Kevin,

J'étais absent la semaine dernière et je n'ai fait la mise à jour qu'aujourd'hui.
C'était bien le point qui bloquait, maintenant c'est fonctionnel dans Home Assistant, juste l'état de la batterie qui n'est pas bon mais pas gênant.

Merci beaucoup pour le cout de main apporté, je voudrais vous remercier à ma manière, j'ai vu sur société.com une adresse (PJ), puis-je envoyer à cette adresse.

Cordialement
Jean Claude LEGUAY

________________________________
De : Kevin Bonnoron ***@***.***>
Envoyé : lundi 2 septembre 2024 08:27
À : KevinBonnoron/the_keys ***@***.***>
Cc : Jclaude49 ***@***.***>; Author ***@***.***>
Objet : Re: [KevinBonnoron/the_keys] Erreur 36 (Issue #31)


Depuis l'application mobile en allant dans la configuration de la serrure, puis tout en bas "Installer la mise à jour".

**Comment by Jclaude49** [comment]
La pièce jointe n'a pas due suivre
![Mes_clés](https://github.com/user-attachments/assets/202126b3-cd07-4160-affb-361479d0a823)

**Comment by KevinBonnoron** [comment]
Bonjour Jclaude.

Tant mieux si c'était bien ça le point bloquant. Oui pour la batterie je ne sais pas précisément comment donner la valeur exacte. J'ai tenté d'utiliser des formules glanées ci et là, mais sans succès.

C'est très gentil de votre part, mais je vais refuser. J'ai fais ce plugin pour aider les gens, et je ne compte pas en tirer le moindre profit. Si ça vous simplifie un peu la vie ça me convient parfaitement.

Je vous conseille cependant de supprimer les captures que vous avez mis. Elles contiennent des informations personelles sur vous et c'est mieux de ne pas les laisser publiques.

Je vous souhaites une bonne journée et n'hésitez surtout pas si vous avez le moindre soucis.

Cordialement,

Kevin Bonnoron
